# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    - src/*.so

before_script:
  - apt-get update && apt-get -y install make gfortran
  - python -V  # Print out python version for debugging
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r etc/CI/requirements.txt

stages:
  - build
  - test
  - doc

compile:
  stage: build
  script:
    - make --directory=src compile

test:
  stage: test
  script:
    - make --directory=src test
  coverage: '/^TOTAL.*\s+(\d+.\d+\%)$/'

pages:
  stage: doc
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
